### ISSUE TITLE
Example for Segment Identify

### ISSUE THREAD

**Issue by zachrnolan** [rangle/redux-beacon#106]
I have page views working with segment, but I can't get an identify event to go through.

Code:

```
const pageView = {
  eventFields: action => ({
    hitType: 'pageview',
    page: action.payload,
  }),
};

const identify = {
  eventFields: action => ({
    hitType: 'identify',
    userId: action.values.id,
  }),
};

const eventsMap = {
  LOCATION_CHANGE: pageView,
  UPDATE_USER_INFO: identify,
};

const segmentMiddleware = createMiddleware(eventsMap, Segment);
```

Is this the proper way to do the identify call? Thanks!

**Comment by zachrnolan** [comment]
Actually looks like my pageviews aren't working either. If anyone can help me out, would be greatly appreciated!

**Comment by zachrnolan** [comment]
Ahh, didn't have the segment script loaded in my html head. It's late =/

**Comment by ttmarek** [comment]
Hahaha @zachrnolan no worries, happens to all of us!

On a serious note, this makes me think we should throw a little warning or an error to the console warning devs that they probably haven't added the segment tag to their page. Here's what I'm thinking.

1. Add a test [here](redux-beacon/src/targets/segment/__tests__/segment.test.js). The test would set `window.analytics = undefined`, and it would `expect(() => Segment()).toThrow('some helpful error message')`. Very similar to the check we have in the Google Analytics target ([last test](redux-beacon/src/targets/google-analytics/__tests__/google-analytics.test.js)).
2. In the [target](redux-beacon/src/targets/segment/segment.js), write a check to ensure that if the window is defined, then `window.analytics` exists. If it doesn't then throw the error. Make the test pass.

Let me know if you want to take this on. If not, then I'll make an issue for it.

**Comment by zachrnolan** [comment]
Thanks for the outline @ttmarek, I went ahead and created a PR for this here: https://github.com/rangle/redux-beacon/pull/108. Let me know if any improvements can be made.
