### ISSUE TITLE
Events stopped being submitted to GTM after updating to v0.4.0

### ISSUE THREAD

**Issue by DinerIsmail** [rangle/redux-beacon#109]
I've noticed that none of the events were submitted to GTM anymore after updating to redux-beacon 0.4.0. I tried to find the reason for this, but I didn't get any errors in the console and nothing else helpful so the only way I could fix it is by reverting back to v0.3.0.
Are there any breaking changes that weren't mentioned? Otherwise this is probably a bug. In that case let me know if there's more info I could to provide to help with this.

**Comment by ttmarek** [comment]
Sorry about that @DinerIsmail.

Yes there was a breaking change in v0.4.0 ([release notes](https://github.com/rangle/redux-beacon/releases/tag/v0.4.0)). We added a feature to allow for renamed dataLayer's. So now you need to call the target before passing it to `createMiddleware` or `createMetaReducer`. 

### Before
```js
 const middleware = createMiddleware(eventsMap, GoogleTagManager);
 const metaReducer = createMetaReducer(eventsMap, GoogleTagManager);
```
### Now
```js

 const middleware = createMiddleware(eventsMap, GoogleTagManager());
 const metaReducer = createMetaReducer(eventsMap, GoogleTagManager());
```

Let me know if that fixes things.

I should have been more explicit about this in the release notes. We'll be using major versions shortly so these kinds of things shouldn't happen anymore.

**Comment by DinerIsmail** [comment]
Yep, that fixes it! Thanks @ttmarek 💯
