### ISSUE TITLE
Help with pushing userId to datalayer

### ISSUE THREAD

**Issue by vivekdwivedi** [rangle/redux-beacon#120]
I am using redux-beacon with react-redux and GTM. Since GA has support for getting logged in user ID from datalayer variable, is there a way to push the userId to datalayer on login and keep in the datalayer till the user logs out?

**Comment by ttmarek** [comment]
Hi @vivekdwivedi.
> is there a way to push the userId to datalayer on login and keep in the datalayer till the user logs out.

Yes. You would need a Redux action to fire whenever the user logs in (e.g. `USER_LOGGED_IN`).
Then you would create an event definition and map it to that event like so:

```javascript
// assumes action.payload contains the userId
const userLogIn = action => ({
  event: 'authentication',
  userId: action.payload,
});

const eventsMap = {
  ...
  USER_LOGGED_IN: userLogIn,
  ...
};
```

This will push the userId to the dataLayer when the user logs in. The userId will remain there in the dataLayer until you change its value to something else. So if you want to have a generic userId for users that aren't logged in, you could fire another event to replace the userId.

```javascript
const userLogOut = () => ({
  event: 'authentication',
  userId: 'unregistered-user',
});

const eventsMap = {
  ...
  USER_LOGGED_OUT: userLogOut,
  ...
};
```
