### ISSUE TITLE
React Native Google Tag Manager integration issue

### ISSUE THREAD

**Issue by apolishch** [rangle/redux-beacon#128]
I have followed the provided documentation (as outlined here)
https://rangle.github.io/redux-beacon/docs/targets/react-native-google-tag-manager.html

Resulting in the following code:

```
import { Platform } from 'react-native'

import { createMiddleware } from 'redux-beacon'
import { GoogleTagManager as GTMBridge } from 'react-native-google-analytics-bridge'
import { GoogleTagManager } from 'redux-beacon/targets/react-native'

import { GTM_ID_ANDROID, GTM_ID_IOS } from '../config'
import { GTM_EVENT_NAME } from '../config'
const containerId = (Platform.OS === 'ios') ? GTM_ID_IOS : GTM_ID_ANDROID
const target = GoogleTagManager(containerId, GTMBridge)
console.log('everything initted')
const eventsMap = {
  'EXAMPLE': (action) => {
    console.log('foo')
    return {
      hitType: GTM_EVENT_NAME
    }
  }
}

const analyticsMiddleware = createMiddleware(eventsMap, GoogleTagManager)

reateStore(
    initStore(AppNavigator, initRoute),
    initData,
    applyMiddleware(ReduxThunk, analyticsMiddleware)
)
```

This results in the following behaviour:
  The application starts up just fine. However, when an 'EXAMPLE' event is emitted, the system crashes with:

```
console.js:26 Possible Unhandled Promise Rejection (id: 0):
Cannot read property 'openContainerWithId' of undefined
TypeError: Cannot read property 'openContainerWithId' of undefined
    at GoogleTagManager (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:100639:12)
    at registerEvents (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:100062:5)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:100026:9
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:99982:16
    at dispatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:53534:18)
    at _callee$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:70225:13)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:21663:40)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:21851:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:21688:21)
    at tryCatch (
```

pointing at: https://github.com/rangle/redux-beacon/blob/master/src/targets/react-native/google-tag-manager/google-tag-manager.js#L2

**Comment by ttmarek** [comment]
Hi @apolishch,

This is odd, it looks like `GoogleTagManager` from `react-native-google-analytics-bridge` is being imported as `undefined`.

A couple things to try:

- re-install `react-native-google-analytics` bridge. Installing React Native modules can be a bit finicky. You might need to follow the [manual installation guide](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Manual-installation).
- If that doesn't work, try rolling back to version `4.0.2`. This is the version @johannalee used in the following example app: https://github.com/johannalee/react-native-redux-example

**Comment by ttmarek** [comment]
@apolishch Did you manage to solve the issue you were having?

**Comment by nikoskleidis** [comment]
I had the same issue. I uninstalled the application on my device and tried to build/install it from the beginning.
The app though could not be built. There was an error mentioning that it couldn't find 
`import com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridgePackage;`
I ended up opening it will android studio and adding react-native-google-analytics-bridge as a module to the project. As a result `compile project(':react-native-google-analytics-bridge')` was added in build.gradle. I believe that this line should have been added during the link process.
After that the project was installed without problems in my device

**Comment by ttmarek** [comment]
Awesome! Thanks for sharing your solution @nikoskleidis.

**Comment by apolishch** [comment]
@ttmarek I did not manage to solve this, and eventually just gave up and went with Firebase Analytics

**Comment by ttmarek** [comment]
Darn. Sorry to hear that @apolishch. 

It looks to be an issue with the `react-native-google-analytics-bridge`. If it comes up again I will bring it up with the maintainers over there.

**Comment by zoltanradics** [comment]
I had the same issue. Initally i realized that `GoogleTagManagerBridge` is undefined in `./node_modules/react-native-google-analytics-bridge/src/GoogleTagManager.js`. So i suspected that something went wrong on the installation of the bridge into xCode. I ended up install the `GoogleTagManagerBridge` manually to our xCode project and it solved the issue. I hope it gives a direction. IF you need detailed information about the manual installation, let me know and i will try to describe it.
