### ISSUE TITLE
working with multiple trackers on one page

### ISSUE THREAD

**Issue by oldo** [rangle/redux-beacon#129]
I have multiple tracking instance running on my site as described [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers). The gist is that you create multiple instance by naming at least one of them:

```
ga('create', 'UA-XXXXX-Y', 'auto');
ga('create', 'UA-XXXXX-Z', 'auto', 'clientTracker');
```

and then target that instance, for example:

```
ga('clientTracker.send', 'pageview');
```

How can I target the named tracker using `redux-beacon`? Is this possible?

**Comment by ttmarek** [comment]
Hi @oldo!

No, unfortunately, our current GoogleAnalytics target doesn't support multiple trackers. We can totally add it though, I think that would be awesome! Do you want to? If so, I can walk you through what to do. It should be pretty straight forward.

Before, we do that though, what would you like the API to look like? My first thought would be to specify a tracker in the event object. Thoughts?

Also, If you need a fix right away, I can show you how you can create your own target that supports this.

**Comment by oldo** [comment]
Hi @ttmarek :-)

Thanks for the enthusiastic response.

Yeah, I would agree that it would make the most sense to just optionally pass `tracker: 'trackerName'` to the event object. If this is not passed then the default unnamed tracker is used, otherwise all actions are prepended with the tracker name.

Also agree that the implementation could be pretty simple but I haven't got the time to look too deeply into the codebase at this stage. Could you give me a little nudge in the right direction?

**Comment by ttmarek** [comment]
Absolutely :slightly_smiling_face: 

The only two files that you'll need to update are:
 1. [`redux-beacon/src/targets/google-analytics/__tests__/google-analytics.test.js`](https://github.com/rangle/redux-beacon/blob/master/src/targets/google-analytics/__tests__/google-analytics.test.js)
 2. [`redux-beacon/src/targets/google-analytics/google-analytics.js`](https://github.com/rangle/redux-beacon/blob/master/src/targets/google-analytics/google-analytics.js)

First, we should make a test or two to ensure that when an event has a `tracker` property we are prefixing the `'send'` string in the `window.ga` call with the name of the tracker.

The test will be almost identical to the first test in `google-analytics.test.js`. The only difference being the events will have custom trackers and our assertions will ensure that `window.ga`'s first argument is prefixed with the appropriate tracker name.

Once that's done, just fiddle with `google-analytics.js` until the test passes.

**Comment by WushuDan** [comment]
@ttmarek Am I right in understanding that the desire is for an event to send to a single named tracker, or is there a desire for an event to go to an array of named trackers, or both?
