### ISSUE TITLE
Outdated documentation for ngrx users

### ISSUE THREAD

**Issue by JacekKosciesza** [rangle/redux-beacon#130]
Documentation for ngrx users is outdated [Redux Beacon Quick Start (ngrx users)](https://rangle.github.io/redux-beacon/docs/quick-start/ngrx-users.html) I was integrating redux-beacon with new version 4.x of ngrx and there are some differences. I made it to work after making those adjustments:

```javascript
// Define an event
const pageView = (action: RouterNavigationAction<RouterStateSnapshot>): PageView => ({
    hitType: 'pageview',
    page: action.payload.routerState.url
});
````
```javascript
// Map the event to an ngrx/store action
const eventsMap = {
    'ROUTER_NAVIGATION': pageView,
};
```

**Comment by ttmarek** [comment]
Hey, thanks for letting me know @JacekKosciesza!

I'll take a look later this evening and push an update accordingly.

**Comment by ttmarek** [comment]
Czesc, @JacekKosciesza.

I've verified this to be true. Thanks again for filing this. I am currently working on a complete overhaul of the ngrx/store example and docs. Stay tuned for an update in the coming days.

**Comment by ttmarek** [comment]
This should be fixed in the latest version. Here's a runnable example that uses ngrx/store v4: https://github.com/rangle/redux-beacon/tree/master/examples/ngrx-store
