### ISSUE TITLE
Wrong page title in Google Analytics

### ISSUE THREAD

**Issue by JacekKosciesza** [rangle/redux-beacon#131]
Problem: there are correct URLs for the pageView in Google Analytics, but page title is incorrect.

I was following [Redux Beacon Quick Start (ngrx users)](https://rangle.github.io/redux-beacon/docs/quick-start/ngrx-users.html) with some modifications (see [Outdated documentation for ngrx users](https://github.com/rangle/redux-beacon/issues/130)) because of the new version 4.x of ngrx.

Problem is that page title is changed in the page component's ngOnInit function:
```typescript
export class DashboardPageComponent implements OnInit {
    constructor(private titleService: Title) { }

    ngOnInit() {
        this.titleService.setTitle('Dashboard | Flex Funding');
    }
}
```
so it is executed some time after ROUTER_NAVIGATION action. As a result I get incorrect (old) page titles in GA:
![image](https://user-images.githubusercontent.com/8171434/30537990-3d3bfb3a-9c6c-11e7-9a15-a51fb71d7e36.png)

I did some workaround by introducing custom action after title is changed, but I would like to have some more generic solution:
```typescript
export class DashboardPageComponent implements OnInit {
    constructor(private store: Store<State>, private titleService: Title, private router: Router) { }

    ngOnInit() {
        this.titleService.setTitle('Dashboard | Flex Funding');
        this.store.dispatch(new AppActions.PageChanged(this.router.routerState.snapshot.url));
    }
}
```
```typescript
const pageView = (action: any): PageView => ({
    hitType: 'pageview',
    page: action.payload
});

// Map the event to an ngrx/store action
const eventsMap: EventDefinitionsMap = {
   //'ROUTER_NAVIGATION': pageView,
   '[app] PAGE_CHANGED': pageView, 
};
```

At least it works:
![image](https://user-images.githubusercontent.com/8171434/30538114-bb58f7e8-9c6c-11e7-9ff5-029495b19365.png)

Any idea how to solve this problem?

**Comment by coluccini** [comment]
What about having the title from the state and pass it to the pageView event definitions using the `nextState` instead leaving GA to use current page's title?

**Comment by ttmarek** [comment]
Hi @JacekKosciesza.

@coluccini is on the money. I would go about your problem in a very similar way.
First I would probably make a map of routes to page titles. Something like:

```js
const pageTitles = {
  '/profile': 'Profile',
  '/accounts/payout': 'Payout',
  '/accounts/deposit': 'Deposit',
};
```

Then I would create a top level reducer to store the current page title in state. The reducer would listen to  each `ROUTER_NAVIGATION` action and update the state using the url from the action payload and the map from above. Then your page view event definition could be written like so:

```ts
const pageView = (
  action: RouterNavigationAction<RouterStateSnapshot>,
  prevState, // won't need this
  nextState,
): PageView => ({
  hitType: 'pageview',
  page: action.payload.routerState.url,
  title: nextState.pageTitle, // or whatever you decide to call this property
});
```
This event definition would give you correct page titles in Google Analytics.

One additional benefit to this approach is you would have a single source of truth for the current page title and you could use this value from state in the `ngOnInit` method.
