### ISSUE TITLE
Create custom target inside React app?

### ISSUE THREAD

**Issue by coluccini** [rangle/redux-beacon#132]
Hi!

I would like to uso a custom target to track events with an internal API. Is there a way I can make the target code inside my app (react/es6 app) or I need to have make it as a compilable package?

**Comment by ttmarek** [comment]
Hey @coluccini.

> Is there a way I can make the target code inside my app (react/es6 app)

Of course! A target is simply a function that Redux-Beacon calls with an array of generated analytics events. What a target does with the array of generated events is up to you, although the assumption is that the target will send those events to an external analytics service.

Here's what it would look like:

```js
// you can have this anywhere, and import it
function myCustomTarget(events) {
  // events is an array of objects [{..},{..}]
  // those objects are the ones returned from your event definitions
}

 const middleware = createMiddleware(eventsMap, myCustomTarget);
```

The segment.io target is pretty simple and might be a good starting point: https://github.com/rangle/redux-beacon/blob/master/src/targets/segment/segment.js

Let me know if this helps 🙂

**Comment by coluccini** [comment]
Thanks! I was trying that and getting errors, so I thought that it wasn't possible. But now I saw that the code had some problems unrelated to this and that was the problem 😬 
Sorry to bother you!

**Comment by ttmarek** [comment]
No problem
