### ISSUE TITLE
Add missing GA events from `react-native-google-analytics-bridge`

### ISSUE THREAD

**Issue by djw27** [rangle/redux-beacon#150]
Hi,

I'd like to add the following events to the redux-beacon RN GoogleAnalyticsTracker:

- setUser()
- trackSocialInteraction()
- trackScreenViewWithCustomDimensionValues()
- trackEventWithCustomDimensionValues()
- trackEventWithCustomDimensionAndMetricValues()
- trackPurchaseEvent()

I'd also like to add the ability to add 'customDimensionsFieldsIndexMap' to the GA tracker.

This is all functionality which I imagine a lot of GA users should need. If you're happy to accept a PR then we'll get it done. Thanks

**Comment by ttmarek** [comment]
@djw27 absolutely!

**Comment by djw27** [comment]
Sorry this has taken so long for me to get round to... I didn't quite get round to adding all the functionality as it wasn't needed: https://github.com/rangle/redux-beacon/pull/174

**Comment by ttmarek** [comment]
New release includes these changes :tada: 
https://rangle.gitbook.io/redux-beacon/targets/react-native-googleanalytics
