### ISSUE TITLE
Usage with react-router-redux@^5

### ISSUE THREAD

**Issue by wyattjoh** [rangle/redux-beacon#173]
It seems that `react-router-redux@^5` is using [`@@router/LOCATION_CHANGE`](https://github.com/ReactTraining/react-router/blob/bb969201817b4ce1667d3933a69497777e1cad15/packages/react-router-redux/modules/reducer.js#L5) instead of `LOCATION_CHANGE` as currently documented in the docs.

Might be a good idea to document that. Also posting so others don't get stuck 😄

**Comment by ttmarek** [comment]
hey @wyattjoh.

The Redux docs are actually written in a framework agnostic way. The `LOCATION_CHANGE` action type was really only meant to communicate that we were listening to an action that dispatches when the route changes, and not that that action comes specifically from `react-router`.

I will be working on improving the docs soon as part of the next release. I will definitely take this into account when re-writing the examples. I really appreciate this sort of feedback, its super helpful. Thank you! 🎖
