### ISSUE TITLE
Make a new npm release

### ISSUE THREAD

**Issue by jessepinho** [rangle/redux-beacon#180]
Looks like the last npm release was 26 October 2017, which means `npm install`ing this package won't include the new features like `GoogleAnalyticsGtag` (which I happen to personally need). Could you publish a new version to npm? Thanks! :)

**Comment by ttmarek** [comment]
@jessepinho 
My apologies. I am currently doing a re-write of the docs that I plan to release with v2.0.0.

I'll be working on it as much as possible tomorrow and on Sunday. I hope to have it out by Monday. I'm so close.

If I don't finish this weekend, I will publish an undocumented alpha version and ping you once its on npm.

**Comment by jessepinho** [comment]
Thanks @ttmarek ! Let me know :)

**Comment by jessepinho** [comment]
@ttmarek BTW, does the current `master` branch represent `v2.0.0`? (Wondering if a simple release of what's currently in master would work?)

Let me know if I can help with the docs somehow! :)

**Comment by ttmarek** [comment]
Yes. Honestly, it may take me a few more days to push the release out.

If all you need is the gtag target, feel free to just copy-paste the target folder into your app somewhere:
https://github.com/rangle/redux-beacon/tree/master/src/targets/google-analytics-gtag

You can also publish this as its own package if you like `redux-beacon-gtag` or whatever. That was actually my hope from the beginning - that a lot of the targets would be published and maintained by the community.

**Comment by jessepinho** [comment]
@ttmarek Ah, that solution works great! (copy-pasting the folder—previously I'd copy-pasted the entire library and that was causing problems haha)

And I like the idea of maintaining the target as a separate library. I'll look into making that happen (a little more complicated than doing it on my own, since it'd prob be owned by my employer). Will check back soon!

**Comment by patricktailor** [comment]
Or, maybe convert the repository to monorepo, with e.g.: [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). Separating the targets and core feature into packages e.g.: `packages/google-analytics`, `packages/google-tag-manager` and `packages/core` and deploy, release the packages to npm.

**Comment by ttmarek** [comment]
@patricktailor this is a great idea. I've thought about it myself...using something like lerna....and I've slowly been moving in that direction. I've got a long todo list that I'm slowly powering through every night to get this next release out. I'll put this in as a nice-to-have/should-have. It doesn't make sense to bump up major versions when a target's api changes.

**Comment by jessepinho** [comment]
@ttmarek I actually had some changes I wanted to make to that target... would it be better for me to open-source a copy of the target or just submit a PR against this repo, then?

**Comment by ttmarek** [comment]
Thats awesome, if you have changes to one of the following targets:

- GoogleAnalytics
- GoogleAnalyticsGtag
- GoogleTagManager
- Segment
- Amplitude
- (RN) GoogleAnalytics
- (RN) GoogleTagManager

Then yeah, please make them. I plan to always support these core targets and keep them a part of this repo.

**Comment by jessepinho** [comment]
@ttmarek will do—thanks!

**Comment by ttmarek** [comment]
### Next release

- [ ] Split targets and extensions into their own packages so they can be versioned individually and published at a faster rate. **WIP**
- [ ] Write typescript definitions for all event helpers
- [ ] Write util: multiple events per action
- [ ] Update core to accept a regex instead of an action type in an events map
- [ ] Write docs: multiple events per action
- [ ] Write docs: Getting Started (ngrx users) **WIP**
- [ ] Write docs: How to Track Pageviews in a React-Redux app 
- [ ] Write docs: How to Track Pageviews in a Angular-ngrx app
- [ ] Write docs: How to Track Pageviews in a Angular-Redux app
- [ ] Write docs: How to Send Analytics to Multiple Targets
- [ ] Write docs: How to Create Your Own Target
- [ ] Write docs: How to troubleshoot AOT issues (needs better title)
- [ ] Write docs: README

**Comment by ttmarek** [comment]
It's out! :champagne: 
https://rangle.gitbook.io/redux-beacon/migration-guide-v1-to-v2
