### ISSUE TITLE
dataLayer.reset();

### ISSUE THREAD

**Issue by williesmithchen** [rangle/redux-beacon#206]
hi all,
i have a question.
sometimes i need call dataLayer.reset();
[sample here](https://www.lunametrics.com/blog/2016/03/21/removing-values-in-the-datalayer/)
how do i call that method use by redux-beacon?

**Comment by ttmarek** [comment]
Hi @williesmithchen, thanks for taking the time to open up an issue.

Question for you: Under what conditions are you reseting the data layer? That is, what is triggering it? Do you want to reset the data layer based on a certain action type. Or is there some other trigger in your application?

**Comment by williesmithchen** [comment]
- Usually this kind of situation happens in e-commerce or use custom dimensions or custom metrics
- spa, transaction complete, page view .....balabala.... 
- yes
- yes. but before send the event need to reset datalayer is required.

here is an sample
```
// buy a captain deadpool toy.
window.dataLayer.push({
  'product' : {
    'name' : 'captain deadpool', 
    'eachPrice' : 199.99,
    'category' : 'toy'
  }
});
// then set a coupon from 3rd party or api response.
window.dataLayer.push({
  'product' : {
    'name' : 'coupon',
    'eachprice' : 0
  }
});
// and send transaction complete....
```

first dataLayer.push(), the gtm datalayer would return a object like
```
 {
    'name' : 'captain deadpool', 
    'eachPrice' : 199.99,
    'category' : 'toy'
 }
```

After the coupon push, the contents will be
```
{
    'name' : 'coupon',
    'eachPrice' : 199.99,
    'category' : 'toy'
}
```

**Comment by ttmarek** [comment]
`window.dataLayer.reset()` anywhere you need it should do the trick
