### ISSUE TITLE
Error: window.datalayer is not defined

### ISSUE THREAD

**Issue by DinerIsmail** [rangle/redux-beacon#207]
I have just updated to Webpack 4, and I am getting an error like in the above screenshot. I am using Redux Beacon right as in the documentation. Do you have any idea what the problem could be? Thanks!

![image](https://user-images.githubusercontent.com/4760294/37146024-7e5d3dca-22ba-11e8-87c3-ddc08ee9ee2a.png)

**Comment by ttmarek** [comment]
Hey @DinerIsmail.

It looks like you're missing the dataLayer function on the window object. Have you included the Google Tag Manager snippet in your `index.html` file as described [here](https://rangle.github.io/redux-beacon/docs/targets/google-tag-manager.html)?

**Comment by DinerIsmail** [comment]
Thanks for replying @ttmarek! I have done that, but it still doesn't work. It has actually worked fine with Webpack 3, just after I updated to Webpack 4 it stopped working. Therefore it might be an issue with Webpack 4 itself, but just wanted to make sure. If you hear of any related issues please let me know :)

**Comment by ttmarek** [comment]
Ah...It could be that the html-webpack-plugin is giving you issues. They [didn't support webpack 4 right away](https://github.com/jantimon/html-webpack-plugin/issues/816). It looks like they might have pushed a new release out: https://github.com/jantimon/html-webpack-plugin/issues/860.
