### ISSUE TITLE
Typescript error when using createMiddleware

### ISSUE THREAD

**Issue by kevinsperrine** [rangle/redux-beacon#215]
This is a...
----
 - [X] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v1.2.1

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [X] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

_(If this is a bug report, feel free to delete the :scroll: and :rocket:
sections. Likewise, if this is a documentation or feature request, feel free to
delete the :beetle: sections)_

:beetle: What are the steps to reproduce your issue?
----
 1. Install v1.2.1 using Typescript
 2. Create a GA middleware using instructions from docs: https://rangle.github.io/redux-beacon/docs/targets/react-native-google-analytics.html
 3. Build

:beetle:  What did you expect to happen?
----
No errors.

:beetle: What happened instead?
----
Typescript throws error ```[ts] Argument of type 'void' is not assignable to parameter of type 'Target'.```

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
 ...Describe the feature or documentation you wish you had.

Can you help out?
----
 - [X] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by kevinsperrine** [comment]
Actually, I guess this has already been fixed in the new code that hasn't been published to npm yet. Thanks! Looking forward to it.

**Comment by ttmarek** [comment]
I'll let you know once it's published! Should be soon, all I have is docs left to do :)

**Comment by ttmarek** [comment]
And....it's out! :slightly_smiling_face: 
https://rangle.gitbook.io/redux-beacon/migration-guide-v1-to-v2

**Comment by kevinsperrine** [comment]
Thanks, @ttmarek!
