### ISSUE TITLE
window.analytics check occurs before eventdefinition is checked for truthiness

### ISSUE THREAD

**Issue by mikebridge** [rangle/redux-beacon#234]
This is a...
----
 - [X] :rocket: Feature Request
Which version of Redux Beacon are you using?

----
 - v 1.2.1

Which target(s) are you using?
----
 - [X] Segment

I have been seeing errors in Rollbar indicating that a variety of clients are generating the error `Uncaught Error: window.analytics is not defined, Have you forgotten to include the Segment tracking snippet?`

My best guess is that some clients are blocking the Segment script or else not evaling it for some reason.  I wanted to turn redux-beacon off for those clients by checking if `window.analytics` is defined in the `EventDefinition` by essentially wrapping each in a function:

```typescript
const ifSegmentDefined = (reducer: EventDefinition): EventDefinition => (
    (action: any, prevState: IMyStore, nextState: IMyStore): any => {
        const w = window as any;
        return w && w.analytics ? reducer(action, prevState, nextState): null;
    }
);
const segmentEventsMap: EventDefinitionsMap = {
    // ...
    [PROFILE.SAVE_SUCCESS]: ifSegmentDefined(myEventDefinition),
}
```

However, this doesn't work because it seems like `redux-beacon` fires the "window.analytics is not defined" error even if my `isSegmentDefined` wrapper returns null or undefined.  It also fires even if I return a literal `null` in my EventDefinition.  I would have expected that the check for `window.analytics` would happen _after_ the check for an empty EventDefinition.

This isn't a big problem---I can work around it by creating a no-op middleware if windows.analytics is undefined.  But I *think* that if there's a race condition on asynchronously loading the segment library, it would be nice to be able to have the check happen when the event is created, not during initialization.

**Comment by ttmarek** [comment]
hey @mikebridge. 

Interesting. Yeah, we are doing a check to ensure that window.analytics exists, if it doesn't we throw an error to let the dev know that it's not there: https://github.com/rangle/redux-beacon/blob/master/packages/segment/src/segment.ts

From what I remember, we added this to make the dev experience a bit better. Rather than getting an obscure error, they'd get a hint as to what the problem is (segment isn't loading, or they didn't add the snippet to their site).

A couple of thoughts...
 - I don't want to get rid of this error, in certain scenarios it's quite helpful 
 - we _could_ add an option to the segment target to oppress "dev warnings" to solve this
 - we _could_ look into creating a dev version (with errors and warnings) and a minified version of the target. Kind of like React...but that may be a bit tricky.

**Comment by mikebridge** [comment]
@ttmarek After I thought about it, I realized that the obvious solution for me was to put the check in middleware.  This a) doesn't throw an exception if the segment initialization is blocked, b) brings the segment integration online if there's a race condition when loading the script asynchronously:

```typescript
export const reduxBeaconSegmentMiddlewareFactory = () => {
    const w = window as any;
    const segmentMiddleWare = createMiddleware(segmentEventsMap, Segment);
    return store => next => action => w && w.analytics ? segmentMiddleWare(store)(next)(action) : next(action);
};
```

I could also write out a warning there if I wanted to instead of absorbing it, or log the problem to Rollbar or NewRelic.

I tested it out with something similar to this:
```typescript
describe("analyticsMiddleware", () => {

    const w = window as any;
    const testId = "123";

    describe("reduxBeaconSegmentMiddlewareFactory", () => {

        it("should not generate a 'windows.analytics is not defined' error if analytics undefined", () => {
            delete w.analytics;
            const mockStore = configureStore([reduxBeaconSegmentMiddlewareFactory()]);
            const store = mockStore(initialStore);
            store.dispatch(createSaveSuccess("123")); // throws exception if error
        });

        it("should call analytics.identify with userid when profile saved", () => {
            let identifiedWithId: string = "";
            w.analytics = mockAnalytics({
                onTrack: () => null,
                onIdentify: (userId: string) => identifiedWithId = userId
            });
            const mockStore = configureStore([reduxBeaconSegmentMiddlewareFactory()]);
            const store = mockStore(initialStore);
            store.dispatch(createSaveSuccess(testId));
            expect(identifiedWithId).toBe(testId);
        });

        it("should call analytics.identify with userid if segment loaded after middleware", () => {
            let identifiedWithId: string = "";
            const mockStore = configureStore([reduxBeaconSegmentMiddlewareFactory()]);
            const store = mockStore(initialStore);
            w.analytics = mockAnalytics({
                onTrack: () => null,
                onIdentify: (userId: string) => identifiedWithId = userId
            });
            store.dispatch(createSaveSuccess(testId));
            expect(identifiedWithId).toBe(testId);
        });

    });
});
```
This seems to work---it would be a fairly easy modification to put this logic directly into `createMiddleware`.

**Comment by ttmarek** [comment]
Glad you came up with something that works! I don't think it makes much sense  to add these checks to `createMiddleware` as this is pretty target-specific. 

P.S.

There's a new version out! Here's the migration guide: https://rangle.gitbook.io/redux-beacon/migration-guide-v1-to-v2

Give it a whirl, let me know if you run into any issues or have an ideas for enhancements. PR's are always welcome! :slightly_smiling_face:
