### ISSUE TITLE
trackPageView event does not pass trackingId

### ISSUE THREAD

**Issue by mattboon** [rangle/redux-beacon#247]
This is a...
----
 - [x] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

Which version of Redux Beacon are you using?
----
 - 1.0.0

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [x] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

:beetle: What are the steps to reproduce your issue?
----
 1. See runnable example I setup as per [setup instructions](https://rangle.gitbook.io/redux-beacon/targets/googleanalyticsgtag): https://codesandbox.io/s/8n5484nl98
 2. Open page in browser: https://8n5484nl98.codesandbox.io
 3. Open developer console
 4. Change route in application
 5. Examine console logged output from `@redux-beacon/logger`

:beetle:  What did you expect to happen?
----
That the payload for the `pageView` event contains the GA Tracking ID in the `trackingId` array.

```
{
  page_location: undefined
  page_path: "/topics"
  page_title: undefined
  trackingId: ["UA-XXXXXX-1"]
  type: "page"
}
```

And that the page view is registered in the Google Analytics dashboard

:beetle: What happened instead?
----

The `trackingId` array is empty:

```
{
  page_location: undefined
  page_path: "/topics"
  page_title: undefined
  trackingId: []
  type: "page"
}
```

And the page view is not registered in Google Analytics

Can you help out?
----
 - [ ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [x] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

I've narrowed the bug down to this block inside `google-analyitics-gtag.js`

```
var trackingIds = [gaTrackingId];
if (typeof trackingId === 'string') {
  trackingIds = [trackingId];
}
if (Array.isArray(trackingId)) {
  trackingIds = trackingId;
}
trackingIds.forEach(function (id) {
  gtag('config', id, params);
});
```

`gtag()` is never called because `trackingIds` is always an empty array.

Should be a a quick fix, but I haven't learned TypeScript yet otherwise I would raise a PR!

**Comment by ttmarek** [comment]
Now _this_ is how you write a bug report. Thanks so much @mattboon! You're a champ! :trophy: 

I just pushed (and published) a fix for this. Here's the diff if you're curious: #248.

I tested the fix myself, but please update to the latest version when you get a chance [`@redux-beacon/google-analytics-gtag@1.0.2`](https://www.npmjs.com/package/@redux-beacon/google-analytics-gtag), and let me know if everything works as it should.

I'm going to close this for now, but feel free to open the issue back up if you're still running into problems.

**Comment by ion-willo** [comment]
I must be missing something. 

My setup is exactly like above and I'm running @redux-beacon/google-analytics-gtag@1.0.2 - no trackingId.

I'm also uncertain where to use the UA-XXX code and where to use the GTM-XXX code
```
 Analytics events @ 12:48:38.715 PAGE_VIEW
  Action: {type: "PAGE_VIEW", payload: "/design-directory-booking-form"}
  Event: {
    type: "page", 
    trackingId: Array(0), 
    page_title: undefined, 
    page_location: "/design-directory-booking-form", 
    page_path: undefined
  }
```

**Comment by ion-willo** [comment]
Hopefulle @mattboon  or @ttmarek can assist
