### ISSUE TITLE
When to use hitType rather than event with Google Tag Manager

### ISSUE THREAD

**Issue by joshuapaling** [rangle/redux-beacon#267]
This is a...
----
 - [ ] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [x] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [x] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
I'm referring to the page at https://rangle.gitbook.io/redux-beacon/targets/googletagmanager, and the lines:

- Only event objects with an event property will trigger a Custom Event in Google Tag Manager.
-  If an event object doesn't have an event property, but has a hitType property, this target will create an event property and set it to the hitType string. 

I'm wondering when and why you'd want to use the `hitType` property? Why not just use the `event` property always? I originally assumed perhaps a `hitType` property might not trigger a custom event, and may be a way of including an 'event' key without triggering an event. But it seems `hitType` will trigger the event. So, why does `hitType` exist?

Thanks for redux-beacon!

Can you help out?
----
 - [x] :star2: I am a legend and can get started on a pull request right away given the go-ahead.

If you think a change to documentation is needed I'm happy to submit the PR.

 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Hey @joshuapaling, good question!

> I'm wondering when and why you'd want to use the hitType property? Why not just use the event property always? 

We added this so we could use the Google Analytics event definition helpers without having to make any changes/customizations: https://rangle.gitbook.io/redux-beacon/targets/googleanalytics#event-definitions.

Essentially we wanted to make Google Tag Manager + Google Analytics integrations as simple as possible. Down the road I'd like us to have a pre-built Google Tag Manager container for Google Analytics integrations. I've discussed the idea briefly here: https://github.com/rangle/redux-beacon/pull/255.

The goal is to make it as easy as:
 - Sign up for GA + GTM
 - Import the GTM Container
 - Setup @redux-beacon/google-tag-manager, and use event definitions from @redux-beacon/google-analytics







This is to make it easier to do Google Tag Manager + Google Analytics integrations.
