### ISSUE TITLE
window.amplitude === undefined

### ISSUE THREAD

**Issue by coluccini** [rangle/redux-beacon#268]
This is a...
----
 - [x] :beetle: Bug Report (not really sure actually, sorry!)

Which version of Redux Beacon are you using?
----
 - v 2.0.3

Which target(s) are you using?
----
 - [x] Amplitude

I've worked a lot with redux-beacon using GTM target and this is my first try with Amplitude. I've follow almost exactly the docs, but when having a few events firing (at least I'm seeing everything ok in the logger) I noticed that the event are not being send to Amplitude. I started going through the code and I've found out that in the `@redux-beacon/amplitude/dist/amplitude.js`, in the following validation
```javascript
if (!window || !window.amplitude) {
   return;
}
```

`window.amplitude` is always undefined...

The code I've have so far is:
```javascript
import { createMiddleware } from 'redux-beacon';
import amplitude from 'amplitude-js';
import Amplitude from '@redux-beacon/amplitude';
import reduxBeaconLogger from '@redux-beacon/logger';
import { logEvent } from '@redux-beacon/amplitude';

amplitude.getInstance().init('1234');
const target = Amplitude({ instance: amplitude.getInstance('INSTANCE_NAME') });

const customEvent = logEvent(action => ({
  type: action.type,
}));

const eventsMap = {
  [TRACK_EVENT]: customEvent,
};

const logger = process.env.NODE_ENV !== 'production' ? reduxBeaconLogger : null;

export default createMiddleware(eventsMap, target, { logger });
```

And the logger is showing this:

<img width="350" alt="screen shot 2018-06-19 at 19 03 06" src="https://user-images.githubusercontent.com/20334179/41612526-7d3a35b2-73f3-11e8-94b1-a542dd9657ef.png">

Am I missing something?

**Comment by ttmarek** [comment]
Hey @coluccini, how's it going?

> Am I missing something?

Nope, you aren't missing anything, you spotted a bug :tada: 

A bug I missed when we added this functionality to Amplitude... :sweat_smile: 

It's a fairly simply fix.

Perhaps something like:

```typescript
const hasProvidedAmplitudeInstance = options && options.instance;

if (!window || (!(window as any).amplitude && !hasProvidedAmplitudeInstance) {
    return;
}
```

**Comment by ttmarek** [comment]
I can make the fix tonight, and push a new version out, unless you'd like to make the change?

**Comment by ttmarek** [comment]
Hi @coluccini.

I had some spare time, so I took the liberty to make the fix. It's available on npm:

```
npm install @redux-beacon/amplitude@1.0.1
```

Everything should work as per the docs now, let me know if it doesn't.

Here's the fix if you're curious: https://github.com/rangle/redux-beacon/pull/269/files

I'll close this issue for now and reopen it if needed.

**Comment by coluccini** [comment]
You are the best @ttmarek! Sorry for not making the changes, I opened the issue right before going to bed and I just woke up with the fix done (an ideal world 😂). I’ll try it as soon I arrive to the office. Thank you soooo much!

**Comment by coluccini** [comment]
Ok, it's working now! 
There is only one issue: in the doc you initialize using `getInstance()` without and instance name and then you pass an instance with a name to the `target`, so they are different instances and the second one is not initialized. After trying, I reach the conclusion that you have to use the same instance name in both places (or use none name).

**Comment by ttmarek** [comment]
That is a bit confusing. You're referring to this line in the `Usage` block?

```typescript
const target = Amplitude({ instance: amplitude.getInstance('INSTANCE_NAME') });
```

It would be clearer to have:

```typescript
const target = Amplitude({ instance: amplitude.getInstance() });
```

Do you agree? If so, feel free to make a PR with the change and I'll push out the docs.
