### ISSUE TITLE
redux-beacon-vuex?

### ISSUE THREAD

**Issue by sergioIGZ** [rangle/redux-beacon#271]
Is there any chance that you start an implementation of this package with Vuex store?

**Comment by ttmarek** [comment]
Hey @sergioIGZ.

Perhaps. It shouldn't be too difficult. It could live under the main [redux-beacon](https://github.com/rangle/redux-beacon/tree/master/packages/redux-beacon) package. Something like `redux-beacon/src/create-plugin.ts`:

```typescript
function createPlugin(
  eventsMap: EventsMap | EventsMapper,
  target: Target,
  extensions: Extensions = {}
) {
  const getEvents =
    typeof eventsMap === 'function'
      ? action => flatten<EventDefinition>([eventsMap(action)])
      : action => getEventsWithMatchingKey(eventsMap, action.type);

  return store => {
    const prevState = store.state;
    store.subscibe((mutation, state) => {
      const events = createEvents(
        getEvents(mutation),
        prevState,
        mutation,
        state
      );

      registerEvents(events, target, extensions, prevState, mutation, state);
    });
  };
}
```

I think that's pretty much it. Would you have any time available to test the above out, and perhaps prep a pr to add it to the repo?

**Comment by kfinley** [comment]
Hey @ttmarek 

I'm interested in using this and have time to test this out and prep a PR to add it if no one else is on it atm.

**Comment by ttmarek** [comment]
@kfinley As far as I know, nobody is working on it. Feel free to give it a go! Don't hesitate to reach out if you have any questions.

**Comment by kfinley** [comment]
@ttmarek While I'd really like to incorporate this into the product the company I'm working for is building I do not have the required support or understanding from the business decision makers to warrant putting in the time to make this work. So for now (unfortunately) I no longer have the need for this so it's up for grabs from anyone.

**Comment by ttmarek** [comment]
No worries at all @kfinley, thanks for following up!
