### ISSUE TITLE
Google Tag Manager - variables

### ISSUE THREAD

**Issue by karolisgrinkevicius** [rangle/redux-beacon#273]
- [ ] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [x] :scroll: Documentation Request

Which version of Redux Beacon are you using?
----
 - 2.0.3

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [x] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
Possibility to add a variable instead of event via target of Google Tag Manager.

Can you help out?
----
 - [x] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
@karolisgrinkevicius Here's the docs file: https://github.com/rangle/redux-beacon/blob/master/docs/targets/google-tag-manager.md

**Comment by karolisgrinkevicius** [comment]
@ttmarek I also cannot see any typescript typings for google tag manager. Afais types are defined in google analytics target.

**Comment by ttmarek** [comment]
Yes that's correct. If you like you're more than welcome to add types. But, I'm not sure how useful they'd be. You can pretty much pass anything to the data layer.

By the way, I've merged your docs changes. They should be live on the site now. Thanks again!

⭐️ 🎉

**Comment by karolisgrinkevicius** [comment]
Regarding ts types I've ended up using already defined type in `redux-beacon`. Please see code snippet below:

```ts
import { EventsMap } from 'redux-beacon';

export const variables: EventsMap = {
  MY_ACTION: action => ({
    myVariable: action.payload.myValue,
  }),
};
```

**Comment by gl0gl0** [comment]
Can you add an example on how it would look a case were events, variables and page views are all mapped in the same EventsMap?
