### ISSUE TITLE
trackEcommAction id should only be required for type purchase or refund.

### ISSUE THREAD

**Issue by leandroz** [rangle/redux-beacon#280]
This is a...
----
 - [X] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v2.0.3

Which target(s) are you using?
----
 - [X] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

_(If this is a bug report, feel free to delete the :scroll: and :rocket:
sections. Likewise, if this is a documentation or feature request, feel free to
delete the :beetle: sections)_

:beetle: What are the steps to reproduce your issue?
----
When tracking an ecommerce action that is not purchase or refund, the id is not required, but in the type definitions it is. Google Analytics documentation:

id | text | Yes* | The transaction ID (e.g. T1234). *Required if the action type is purchase or refund.

I think we should make it optional so we don't force a value.

Can you help out?
----
 - [ ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [X] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Hey @leandroz. I had a bit of extra time this weekend. This should be fixed in `@redux-beacon/google-analytics@1.0.4`. I went ahead and updated all the other enhanced ecomm event helpers as well to match the docs. We are also throwing an error when a dev forgets to provide an `id` or `name` as it looks like GA will just fail silently there.

**Comment by leandroz** [comment]
That's awesome @ttmarek, just checked the PR, looks great, thanks for that!
