### ISSUE TITLE
debounceEvent and google tag manager console error

### ISSUE THREAD

**Issue by karolisgrinkevicius** [rangle/redux-beacon#282]
This is a...
----
 - [x] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v2.0.3

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [x] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

:beetle: What are the steps to reproduce your issue?
----
 1. Using target `google-tag-manager` add `debounceEvent` in combination
2. Return `undefined` instead of fulfilled event, i.e.:
```jsx
import debounceEvent from '@redux-beacon/debounce-event';
import { EventsMap } from 'redux-beacon';

return {
  MY_REDUX_ACTION: debounceEvent(100, () => {
    if (false) {
      return {
        event: 'event'
      };
    }
  })
};
```

:beetle:  What did you expect to happen?
----
 _No error is thrown into console, event should be omitted from the data layer._

:beetle: What happened instead?
----
 _...Error is thrown `Uncaught (in promise) TypeError: Cannot read property 'event' of undefined`.._

Can you help out?
----
 - [x] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Fixed in `@redux-beacon/google-tag-manger@1.0.1`.
