### ISSUE TITLE
Redux Beacon Google Tag Manager docu down

### ISSUE THREAD

**Issue by johannesluedke** [rangle/redux-beacon#293]
This is a...
----
 - [x] :beetle: Bug Report
 - [x] :scroll: Documentation Request

https://rangle.gitbook.io/redux-beacon/targets/googletagmanager gives a 404 and ​"GoogleTagManager: Setup"​ is crossed out on https://rangle.gitbook.io/redux-beacon/getting-started-redux-users

https://github.com/rangle/redux-beacon/blob/master/docs/getting-started-redux-users.md seems to be the right link?

**Comment by ttmarek** [comment]
Thanks for this. I'm aware of this issue, and I'm working with the Gitbook.io team to figure out why. Sorry about the delay. The correct link is: 

https://rangle.gitbook.io/redux-beacon/index/google-tag-manager

Worst case scenario we could hard code this in. But, in theory this should all be taken care of by gitbook.

**Comment by ttmarek** [comment]
I'm still not sure why Gitbook is boycotting the Google Tag Manager page specifically. I added a temporary solution that (unfortunately) opens the docs in a new tab. Its the best I can do for now until I hear back from the Gitbook team.
