### ISSUE TITLE
trackException() sending incorrect fields object

### ISSUE THREAD

**Issue by afholderman** [rangle/redux-beacon#294]
This is a...
----
 - [ X ] :beetle: Bug Report

Which version of Redux Beacon are you using?
----
 - @redux-beacon/google-analytics@1.1.0

Which target(s) are you using?
----
 - [ X ] Google Analytics

:beetle: What are the steps to reproduce your issue?
----
 1. Change Google Analytics tag to debug mode: https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging
 2. Register an exception event:
 ``ActionType: trackException((action: Type) => ({
      description: 'foo',
      isFatal: false
  })``
 3. Fire event in the browser
4. Check console to find the following:
```
Executing Google Analytics commands.
analytics_debug.js:22
Running command: ga("send", {hitType: "exception", customTrackerId: undefined, description: "TypeError: Failed to fetch", isFatal: undefined})
analytics_debug.js:22
Set called on unknown field: "customTrackerId".
analytics_debug.js:22
Set called on unknown field: "description".
analytics_debug.js:22
Set called on unknown field: "isFatal".
index.js:1452
Missing required field '"exDescription"' for hit of type '"exception"'
```

:beetle:  What did you expect to happen?
----
ga send event should complete without errors.

:beetle: What happened instead?
----
Error appeared in console.

The bug derives from the typing in event-helpers.ts. Changing `description` and `isFatal` to `exDescription` and `exFatal` solves the issue.

Problem block in code:
https://github.com/rangle/redux-beacon/blob/master/packages/google-analytics/src/event-helpers.ts#L87

Docs showing correct fields:
https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

Can you help out?
----
 - [ X  ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Thanks so much! This is live:

```
npm install @redux-beacon/google-analytics@1.1.1
```

Sorry for the delay.
