### ISSUE TITLE
How are we meant to test this?

### ISSUE THREAD

**Issue by smksnutmeg** [rangle/redux-beacon#299]
Just a simple question on testing our eventMap with Beacon. There is no documentation on how we can test so this is what I have for routing.

*routing.js*

```javascript
import { trackPageView } from '@redux-beacon/segment';
import { LOCATION_CHANGE } from 'react-router-redux';

const eventsMap = {
  [LOCATION_CHANGE]: trackPageView(() => ({}))
};

export default eventsMap;
```

*routing.spec.js*
```javascript
import eventsMap from './routing';

const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const locationPayload = {
  hitType: 'pageview',
  name: undefined,
  options: undefined,
  page: undefined,
  properties: undefined
};

describe('Given the routing events', () => {
  it('should have the correct action type', () => {
    expect(eventsMap[LOCATION_CHANGE]).toBeDefined();
  });

  describe('when we change Route', () => {
    let event;

    beforeEach(() => {
      event = eventsMap[LOCATION_CHANGE];
    });

    it('should fire a trackPageView action', () => {
      expect(event()).toEqual(locationPayload);
    });
  });
});
```

**Comment by ttmarek** [comment]
Hi @smksnutmeg.

That's a good question. If you have logic within your event definitions then you can test those as simple pure functions. In theory this is all you should need. If you want to test more you'd just be testing redux-beacon itself, and we've already got that covered here haha.

If your hands are tied and you're trying to meet a some tough coverage requirements you can do an integration test using an (as of yet) undocumented helper that we use internally called `createEvents`:

```typescript
import { createEvents } from 'redux-beacon';
```

Here is the type definition for the function: https://github.com/rangle/redux-beacon/blob/master/packages/redux-beacon/src/create-events.ts

In your test you prepare the inputs to the helper, and assert the expected events that you want passed onto the target. I wouldn't recommend this per se. It's just an option in case you absolutely feel you need to do the integration test.
