### ISSUE TITLE
Documentation request: please remove the Github Pages docs

### ISSUE THREAD

**Issue by JasonNutmeg** [rangle/redux-beacon#302]
This is a...
----
 - [ ] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [x] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - NA

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [X] Segment

----
 - [ ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [x] :disappointed: I won't be able to help out on this one.

The documentation on [https://rangle.github.io/redux-beacon](https://rangle.github.io/redux-beacon) is out-of-date and some pages are no longer needed. If I understand correctly, the GitBook docs are the most relevant.

It's been very misleading when reading the old docs and finding out that the content isn't accurate.

The old docs are high-ranking when searching on Google, so I can imagine other people have encountered the same problem.

**Comment by ttmarek** [comment]
Yup, I hope to have some time in the coming weeks to do this. I will set up redirects where necessary. I'd like to piggyback on the high ranking search results. Thanks for the nudge 😉

**Comment by JasonNutmeg** [comment]
Sounds good to me!
Thanks for addressing it :)

**Comment by ttmarek** [comment]
All pages that show up in Google now redirect to the new docs site.
