### ISSUE TITLE
Documentation Bug: Broken links on readme.md

### ISSUE THREAD

**Issue by UiCandy** [rangle/redux-beacon#305]
This is a...
----
 - [ ] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [x] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [x] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [ ] Other/Third Party: ...(please specify here)

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
 _The links to the documentation on the readme.md are broken_

Can you help out?
----
 - [x] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [ ] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Thanks! I just went through the docs and fixed any broken links I could find. Let me know if you come across anything else. 

Happy new year!
