### ISSUE TITLE
How to track external link when each link has its own metadata?

### ISSUE THREAD

**Issue by nuttakornbe** [rangle/redux-beacon#306]
Same as the topic. Does redux-beacon support this?

**Comment by ttmarek** [comment]
Hi @nuttakornbe,

You're going to have to be a bit more descriptive here. The title doesn't give me quite enough context for me to help you out.

What exactly would you like to track? Would you like to track that a user has clicked on an external link (a link to somewhere outside of your app)? Also....what target are you using?

**Comment by gl0gl0** [comment]
I have same/similar question, I put it here:
https://stackoverflow.com/questions/54807396/react-redux-beacon-track-link-clicks-analytics
🙏🏼

**Comment by ttmarek** [comment]
This was answered on StackOverflow: https://stackoverflow.com/questions/54807396/react-redux-beacon-track-link-clicks-analytics
