### ISSUE TITLE
Error when trying to track e-commerce items in GA following documentation

### ISSUE THREAD

**Issue by wermetal** [rangle/redux-beacon#333]
This is a...
----
 - [x] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

Which version of Redux Beacon are you using?
----
 - v 2.0.5

Which target(s) are you using?
----
 - [x] Google Analytics

:beetle: What are the steps to reproduce your issue?
----
If you follow the documentation to track ecommerce items (products), probably you will write code like
```js
import { createMiddleware } from 'redux-beacon';
import { ecommSend, trackEcommItem } from '@redux-beacon/google-analytics';

const ecommItem = trackEcommItem((action, prevState, nextState) => {
  return {/*some item here*/};
}

const ecommSendSignal = ecommSend(/* (optional) tracker name */);

const eventMap = {
  ADD_ITEM: ecommItem,
  SEND: ecommSendSignal
}

...

const ga = GoogleAnalytics();
const gaMiddleware = createMiddleware(eventMap, ga);
...
```

But when you will try to send your items to GA you will get next error 
```js
Uncaught (in promise) TypeError: eventDef is not a function
    at eval (create-events.js?ee0c:17)
    at Array.map (<anonymous>)
    at Object.createEvents [as default] (create-events.js?ee0c:16)
    at eval (create-middleware.js?47d1:35)
```

This happens because all event helpers like `trackEcommItem`, `trackEvent`, `trackPageView` return functions, but event helpers `ecommSend` and `ecommClear` return plain objects. But function `createEvents` in `create-events.ts` expects that all values in `eventMap` will be functions. 
You have an error in the documentation or in the code. I see three ways to fix this bug:
1. Edit the documentation and suggest to wrap `ecommSend` in function like:
`
const ecommSendSignal = () => ecommSend(/* (optional) tracker name */);
`
2. Edit code and remake `ecommSend` and `ecommClear` to return a function.
3. Edit code and remake `createEvents` to let it work both with functions and objects

Can you help out?
----
 - [x] :star2: I can do this, but only when owners of the repository make a decision what to do.

**Comment by ttmarek** [comment]
@wermetal Great catch!

Sorry for the late reply. I was out of country for a client.

It's an issue with the event definition helpers here: [event-helpers.ts](https://github.com/rangle/redux-beacon/blob/master/packages/google-analytics/src/event-helpers.ts#L152-L160).

Notice how every other event definition helper returns the `: EventDefinition<any, A, S>` type? We should update both `ecommSend` and `ecommClear` to do that as well.

So, option #2 in your suggestions! 😄 

Let me know if you need any help making the changes.
