### ISSUE TITLE
Update docs for usage with React Native + Segment

### ISSUE THREAD

**Issue by ivansantosz** [rangle/redux-beacon#337]
This is a...
----
 - [ ] :beetle: Bug Report
 - [ ] :rocket: Feature Request
 - [x] :scroll: Documentation Request

**Note:** for support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/redux-beacon) with the `redux-beacon` tag. This repository's issues are reserved for feature requests and bug reports.

Which version of Redux Beacon are you using?
----
 - v2.1.0

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [x] Segment
 - [ ] Other/Third Party: ...(please specify here)

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
 _Update documentation for Segment integration with React Native. It only shows using it in the browser getting key configurations from lib, but not directly from react native_

Can you help out?
----
 - [ ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [x] :star: I would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by ttmarek** [comment]
Hi!

We actually don't have a React Native + Segment Target yet. We have a pull request for one [here](https://github.com/rangle/redux-beacon/pull/321), but it's a bit stale and it doesn't look like it'll cross the finish line. If you like you can create a new one based on what was already done.

Keep in mind that a target doesn't have to be associated with this repo/package at all. You can build and provide your own custom targets for any service: https://rangle.gitbook.io/redux-beacon/examples-and-recipes#how-to-create-your-own-target
