### ISSUE TITLE
Add Matomo (formerly Piwik) support

### ISSUE THREAD

**Issue by dbartholomae** [rangle/redux-beacon#338]
This is a...
----
 - [ ] :beetle: Bug Report
 - [X] :rocket: Feature Request
 - [ ] :scroll: Documentation Request

Which version of Redux Beacon are you using?
----
 - v 2.1.0

Which target(s) are you using?
----
 - [ ] Google Analytics
 - [ ] Google Analytics (gtag)
 - [ ] React Native Google Analytics
 - [ ] Google Tag Manager
 - [ ] React Native Google Tag Manager
 - [ ] Amplitude
 - [ ] Segment
 - [X] Other/Third Party: Matomo (formerly Piwik)

:rocket: :scroll: What's missing from Redux Beacon that you'd like to add?
----
A plugin to use [Matomo (formerly Piwik) Tag Manager](https://developer.matomo.org/guides/tagmanager/introduction) would be great! :)
We will be able to take most of the work, but would appreciate a go-ahead and some guidance / PR review.

Can you help out?
----
 - [ ] :star2: I am a legend and can get started on a pull request right away given the go-ahead.
 - [X] :star: I am a superstar and would like to help out given some guidance.
 - [ ] :disappointed: I won't be able to help out on this one.

**Comment by dbartholomae** [comment]
Here's the repo:
https://github.com/dbartholomae/redux-beacon-matomo-tag-manager

**Comment by ttmarek** [comment]
Awesome! This is very much appreciated. I've added a spot in the docs and README for third-party targets like these. 🏅
