### ISSUE TITLE
Integration with Redux Dynamic Modules

### ISSUE THREAD

**Issue by dbartholomae** [rangle/redux-beacon#341]
In case someone is interested: I have written an extension for [Redux Dynamic Modules](https://github.com/microsoft/redux-dynamic-modules) that allows to connect to redux-beacon.
Redux Dynamic Modules is a library that allows to modularize redux code. With help of this extension events do not have to be defined in one central location but can be defined for each module individually.

The extension can be found [here](https://github.com/dbartholomae/redux-dynamic-modules-beacon).

The corresponding ticket in the other repo can be found here:
https://github.com/microsoft/redux-dynamic-modules/issues/95

**Comment by ttmarek** [comment]
This looks awesome, thanks for taking the time to do this! It's much appreciated.

I'm going to close this as it isn't really an issue, but I am more than happy to accept a PR that mentions or links to this in the docs.
