### ISSUE TITLE
The first line of the logger could be more useful

### ISSUE THREAD

**Issue by ttmarek** [rangle/redux-beacon#54]
It just says Analytics. Not really informative.

![image](https://cloud.githubusercontent.com/assets/7446702/23712039/95b8c5d8-03ef-11e7-8689-c412cfaad19e.png)

A few options:

 * **`Analytics events triggered by: NAME_ENTERED`**
 * **`analytics events from: NAME_ENTERED`**
 * **`NAME_ENTERED --> Analytics`**
 * **`NAME_ENTERED --> Analytics Events`**
 * **`Analytics from NAME_ENTERED`**
 * **`Analytics from NAME_ENTERED @ 14:43:59.315`**

**Comment by bertrandk** [comment]
My vote is for `Analytics events @ 14:43:59.315 NAME_ENTERED`

**Comment by ttmarek** [comment]
**`Analytics events @ 14:43:59.315 NAME_ENTERED`**

**Comment by AllDayAlone** [comment]
It would be very useful to see for which target event was fired in case you add the logger to multiple middleware @ttmarek
