### ISSUE TITLE
Forbidden trailing comma in Typings

### ISSUE THREAD

**Issue by philipptri** [rangle/redux-beacon#69]
There's a typo in the type definitions:

```
ERROR in redux-beacon/index.d.ts
(65,14): error TS1009: Trailing comma not allowed.
```

**Comment by ttmarek** [comment]
Hey @philipptri! Thanks for bringing this up. Trailing commas in function parameter lists are valid with my current Typescript version and `tsconfig`. May I ask what Typescript version you're using? Either way, I think I'd accept a PR to remove it from Redux Beacon's type definitions if you're up for it.

**Comment by philipptri** [comment]
Hi @ttmarek! Good point, that might be the reason. We are still on `1.4.0` but we will update soon as well.

Thanks!
