### ISSUE TITLE
rename dataLayer

### ISSUE THREAD

**Issue by sombreroEnPuntas** [rangle/redux-beacon#97]
As detailed on [GTM docs](https://developers.google.com/tag-manager/devguide#renaming), it is possible to rename the data layer instance.

Default name is `dataLayer`.
If I change it to something else, how can I tell redux-beacon to use the new name?

Thanks!

**Comment by ttmarek** [comment]
Hi @sombreroEnPuntas. That's a great idea! Thanks for taking the time to open up an issue and make a pull request (#98) ! Let me have a look at it now.
